version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: helmet
    versions:
    - 4.4.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: mongoose
    versions:
    - 5.11.13
    - 5.11.14
    - 5.11.15
    - 5.11.16
    - 5.11.17
    - 5.11.18
    - 5.11.19
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
  - dependency-name: "@types/mongoose"
    versions:
    - 5.10.3
    - 5.10.4
  - dependency-name: ts-jest
    versions:
    - 26.4.4
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: typescript
    versions:
    - 3.9.7
    - 3.9.8
    - 3.9.9
  - dependency-name: lint-staged
    versions:
    - 10.5.3
    - 10.5.4
  - dependency-name: "@types/lodash"
    versions:
    - 4.14.168
  - dependency-name: uuid
    versions:
    - 8.3.2
  - dependency-name: "@types/morgan"
    versions:
    - 1.9.2
  - dependency-name: bl
    versions:
    - 2.2.1
