# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Node module directory
        uses: actions/checkout@v2
        
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      
      - name: Install Dependencies
        if: success()
        run: npm install
      
      - name: Check Lint Issues
        if: success()
        run: npm run lint
        
      - name: Check Prettier Issues
        if: success()
        run: npm run prettier
        
      - name: Run Test Cases
        if: success()
        run: npm run test --if-present

      - name: Fetch Config
        if: success()
        id: configfetch
        uses: anant-sharma/chip-config-fetch@v2.9.0
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Set up Docker Buildx
        if: success()
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Dockerhub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ steps.configfetch.outputs.DOCKER_USER }}
          password: ${{ steps.configfetch.outputs.DOCKER_PASS }}

      - name: Build and Push Image
        if: success()
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{steps.configfetch.outputs.DOCKER_USER}}/${{steps.configfetch.outputs.DOCKER_IMAGE_NAME}}:${{steps.configfetch.outputs.TAG}}

      - name: Deploy to Chip Cluster
        if: success()
        uses: anant-sharma/chip-config-fetch@v2.9.0
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          deploy: "1"

      - name: Slack Notification
        uses: 8398a7/action-slack@v2
        if: always()
        with:
          status: ${{ job.status }}
          author_name: ${{ env.GITHUB_ACTOR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ steps.configfetch.outputs.SLACK_WEBHOOK }}
