# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    branches: [master]
    types: 
      - completed
      - requested
jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Chip Cluster
        id: deploy
        uses: anant-sharma/chip-config-fetch@v2.9.0
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          deploy: "1"

      - name: Slack Notification
        uses: 8398a7/action-slack@v2
        if: always()
        with:
          status: ${{ job.status }}
          author_name: ${{ env.GITHUB_ACTOR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ steps.deploy.outputs.SLACK_WEBHOOK }}
